name: Auto Update Toffee
on:
  schedule:
    - cron: '0 */4 * * *' # Proti 4 ghonta por por
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run Script
        run: python update_toffee.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Toffee.m3u
          git commit -m "Auto Update Cookie" || exit 0
          git push
