name: Toffee Fully Auto
on:
  schedule:
    - cron: '0 * * * *' # Proti ghontay run hobe
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Run Script
        run: |
          pip install requests
          python update_toffee.py
      - name: Commit and Push
        run: |
          git config --global user.name "Auto-Updater"
          git config --global user.email "bot@github.com"
          git add Toffee.m3u
          git commit -m "Cookie updated automatically" || exit 0
          git push
